44.85 Failed to compile. 44.85 44.85 app/api-keys/page.tsx 44.85 Type error: File '/app/app/api-keys/page.tsx' is not a module. 44.85 44.89 Static worker exited with code: 1 and signal: null ------
 3 warnings found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 30)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 56)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 57)
Dockerfile:24
--------------------
  22 |
  23 |     # Build the application
  24 | >>> RUN npm run build
  25 |
  26 |     # Production image, copy all the files and run next
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1